testing 2nd half of deploy script

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -53,17 +53,17 @@ jobs:
       with:
         inlineScript: |
           az group create --name $TESTRESOURCEGROUPNAME --location $AZURELOCATION
-          echo "Creating publicly exposed cluster and waiting to become active"
-          az group deployment create --name $TESTDEPLOYMENTNAME --resource-group $TESTRESOURCEGROUPNAME --template-file azuredeploy.json --parameters ci/azuredeploy.parameters.json
-          az group show --name $TESTRESOURCEGROUPNAME | grep provisioningState
-          export url=`az network public-ip show --resource-group $TESTRESOURCEGROUPNAME --name myLBPublicIPD --query [ipAddress] --output tsv`; echo $url
-          curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64; tar -xvf SDKPERF_C_LINUX64 -C /tmp; /tmp/pubSubTools/sdkperf_c -cip=$url -mn=100000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
-          sleep 30
-          bash -c 'if [[ -z `curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>" | grep "<oper-status>Up</oper-status>"` ]] ; then echo "config-sync not up!"; exit 1; fi'
-          curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><redundancy></redundancy></show></rpc>"
-          curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>"
-          az group deployment create -g $TESTRESOURCEGROUPNAME -f ci/ResourceGroupCleanup.template.json --mode complete # purge all existing resources from RG to prep for next deployment
-          az deployment delete --name $TESTDEPLOYMENTNAME
+          # echo "Creating publicly exposed cluster and waiting to become active"
+          # az group deployment create --name $TESTDEPLOYMENTNAME --resource-group $TESTRESOURCEGROUPNAME --template-file azuredeploy.json --parameters ci/azuredeploy.parameters.json
+          # az group show --name $TESTRESOURCEGROUPNAME | grep provisioningState
+          # export url=`az network public-ip show --resource-group $TESTRESOURCEGROUPNAME --name myLBPublicIPD --query [ipAddress] --output tsv`; echo $url
+          # curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64; tar -xvf SDKPERF_C_LINUX64 -C /tmp; /tmp/pubSubTools/sdkperf_c -cip=$url -mn=100000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
+          # sleep 30
+          # bash -c 'if [[ -z `curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>" | grep "<oper-status>Up</oper-status>"` ]] ; then echo "config-sync not up!"; exit 1; fi'
+          # curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><redundancy></redundancy></show></rpc>"
+          # curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>"
+          # az group deployment create -g $TESTRESOURCEGROUPNAME -f ci/ResourceGroupCleanup.template.json --mode complete # purge all existing resources from RG to prep for next deployment
+          # az deployment delete --name $TESTDEPLOYMENTNAME
 
     - name: Test deploy with internally exposed cluster option
       uses: azure/CLI@v1
