test run without Azure inline script

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -34,6 +34,14 @@ jobs:
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
+    # - name: Setup Azure CLI and login
+    #   run: |
+    #     AZ_REPO=$(lsb_release -cs)
+    #     echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
+    #     curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
+    #     sudo apt-get install apt-transport-https
+    #     sudo apt-get install azure-cli
+    #     az login `echo ${{ secrets.AZURE_CREDENTIALS }}`
     
     - name: Lint json templates
       run: |
@@ -49,44 +57,40 @@ jobs:
         cat ci/azuredeploy.parameters.json
 
     - name: Test deploy with public LB option
-      uses: azure/CLI@v1
-      with:
-        inlineScript: |
-          az group create --name $TESTRESOURCEGROUPNAME --location $AZURELOCATION
-          # echo "Creating publicly exposed cluster and waiting to become active"
-          # az group deployment create --name $TESTDEPLOYMENTNAME --resource-group $TESTRESOURCEGROUPNAME --template-file azuredeploy.json --parameters ci/azuredeploy.parameters.json
-          # az group show --name $TESTRESOURCEGROUPNAME | grep provisioningState
-          # export url=`az network public-ip show --resource-group $TESTRESOURCEGROUPNAME --name myLBPublicIPD --query [ipAddress] --output tsv`; echo $url
-          # curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64; tar -xvf SDKPERF_C_LINUX64 -C /tmp; /tmp/pubSubTools/sdkperf_c -cip=$url -mn=100000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
-          # sleep 30
-          # bash -c 'if [[ -z `curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>" | grep "<oper-status>Up</oper-status>"` ]] ; then echo "config-sync not up!"; exit 1; fi'
-          # curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><redundancy></redundancy></show></rpc>"
-          # curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>"
-          # az group deployment create -g $TESTRESOURCEGROUPNAME -f ci/ResourceGroupCleanup.template.json --mode complete # purge all existing resources from RG to prep for next deployment
-          # az deployment delete --name $TESTDEPLOYMENTNAME
+      run: |
+        az group create --name $TESTRESOURCEGROUPNAME --location $AZURELOCATION
+        # echo "Creating publicly exposed cluster and waiting to become active"
+        # az group deployment create --name $TESTDEPLOYMENTNAME --resource-group $TESTRESOURCEGROUPNAME --template-file azuredeploy.json --parameters ci/azuredeploy.parameters.json
+        # az group show --name $TESTRESOURCEGROUPNAME | grep provisioningState
+        # export url=`az network public-ip show --resource-group $TESTRESOURCEGROUPNAME --name myLBPublicIPD --query [ipAddress] --output tsv`; echo $url
+        # curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64; tar -xvf SDKPERF_C_LINUX64 -C /tmp; /tmp/pubSubTools/sdkperf_c -cip=$url -mn=100000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
+        # sleep 30
+        # bash -c 'if [[ -z `curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>" | grep "<oper-status>Up</oper-status>"` ]] ; then echo "config-sync not up!"; exit 1; fi'
+        # curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><redundancy></redundancy></show></rpc>"
+        # curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>"
+        # az group deployment create -g $TESTRESOURCEGROUPNAME -f ci/ResourceGroupCleanup.template.json --mode complete # purge all existing resources from RG to prep for next deployment
+        # az deployment delete --name $TESTDEPLOYMENTNAME
 
     - name: Test deploy with internally exposed cluster option
-      uses: azure/CLI@v1
-      with:
-        inlineScript: |
-          UNIQUEID2="$(date +%s)"
-          sed -i 's@"Public"@"Internal"@g' ci/azuredeploy.parameters.json
-          sed -i "s@\"ghactionsws.*@\"ghactionsws${UNIQUEID2}\"@g" ci/azuredeploy.parameters.json
-          cat ci/azuredeploy.parameters.json
-          echo "Creating internally exposed cluster and waiting to become active"
-          az deployment group create --name TravisTestDeployment${UNIQUEID2} --resource-group $TESTRESOURCEGROUPNAME --template-file azuredeploy.json --parameters ci/azuredeploy.parameters.json
-          az group show --name $TESTRESOURCEGROUPNAME | grep provisioningState
-          az network vnet subnet create  --address-prefixes "10.0.1.0/24" --name VmTestSubnet -g $TESTRESOURCEGROUPNAME --vnet-name solace-vnet
-          az vm create   --resource-group $TESTRESOURCEGROUPNAME --name myVM   --image UbuntuLTS  --vnet-name solace-vnet  --subnet VmTestSubnet --admin-username azureuser   --generate-ssh-keys
-          VM_IP=`az vm show -d -g $TESTRESOURCEGROUPNAME -n myVM --query publicIps -o tsv`
-          LB_IP=`az network lb show -g $TESTRESOURCEGROUPNAME -n solace-ha-group-loadbalancer    --query "frontendIpConfigurations[].privateIpAddress" -o tsv`
-          echo ${VM_IP}
-          echo ${LB_IP}
-          ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "curl ${LB_IP}:8080" | grep aurelia
-          ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "curl -sS -u admin:$ADMINPASSWORD http://${LB_IP}:8080/SEMP -d \"<rpc><show><redundancy></redundancy></show></rpc>\" "
-          ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64 ; tar -xvf SDKPERF_C_LINUX64"
-          ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "pubSubTools/sdkperf_c -cip=${LB_IP}:55555 -mn=100000 -mr=0 -ptl=t1 -stl=t1" | grep "Total Messages"
-          echo "Test complete"
+      run: |
+        UNIQUEID2="$(date +%s)"
+        sed -i 's@"Public"@"Internal"@g' ci/azuredeploy.parameters.json
+        sed -i "s@\"ghactionsws.*@\"ghactionsws${UNIQUEID2}\"@g" ci/azuredeploy.parameters.json
+        cat ci/azuredeploy.parameters.json
+        echo "Creating internally exposed cluster and waiting to become active"
+        az deployment group create --name TravisTestDeployment${UNIQUEID2} --resource-group $TESTRESOURCEGROUPNAME --template-file azuredeploy.json --parameters ci/azuredeploy.parameters.json
+        az group show --name $TESTRESOURCEGROUPNAME | grep provisioningState
+        az network vnet subnet create  --address-prefixes "10.0.1.0/24" --name VmTestSubnet -g $TESTRESOURCEGROUPNAME --vnet-name solace-vnet
+        az vm create   --resource-group $TESTRESOURCEGROUPNAME --name myVM   --image UbuntuLTS  --vnet-name solace-vnet  --subnet VmTestSubnet --admin-username azureuser   --generate-ssh-keys
+        VM_IP=`az vm show -d -g $TESTRESOURCEGROUPNAME -n myVM --query publicIps -o tsv`
+        LB_IP=`az network lb show -g $TESTRESOURCEGROUPNAME -n solace-ha-group-loadbalancer    --query "frontendIpConfigurations[].privateIpAddress" -o tsv`
+        echo ${VM_IP}
+        echo ${LB_IP}
+        ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "curl ${LB_IP}:8080" | grep aurelia
+        ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "curl -sS -u admin:$ADMINPASSWORD http://${LB_IP}:8080/SEMP -d \"<rpc><show><redundancy></redundancy></show></rpc>\" "
+        ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64 ; tar -xvf SDKPERF_C_LINUX64"
+        ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "pubSubTools/sdkperf_c -cip=${LB_IP}:55555 -mn=100000 -mr=0 -ptl=t1 -stl=t1" | grep "Total Messages"
+        echo "Test complete"
 
 
     - name: Delete test resource group (Cleanup)
